---
title: Kevin Rei
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
bio: My passion lies in two types of programming.
description: An average Japanese-Filipino Houstonian who loves video games and all
  things mobile.
reading_time: true
words_per_minute: 200
logo: assets/img/logo.png
background: assets/img/sunset.jpg
locale: en_US
permalink: "/:title/"
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
mathjax: true
sass:
  sass_dir: _sass
  style: compressed
disqus_shortname: kevinrei
facebook: kevinreimateo
twitter: GlacierxRei
instagram: glacier_rei
linkedin: kevinreimateo
github: kevinrei
gems:
- jekyll-mentions
- jekyll-feed
- jekyll-sitemap
- jekyll-gist
jekyll-mentions:
  base_url: https://github.com
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
- package.json
- _site
- src
- vendor
- CNAME
- LICENSE
- Rakefile
